//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReportResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportResources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Resources.ReportResources", typeof(ReportResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Отчет.
        /// </summary>
        internal static string SheetTitle_Report {
            get {
                return ResourceManager.GetString("SheetTitle_Report", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Сравнение периодов.
        /// </summary>
        internal static string SheetTitle_PeriodsComparison {
            get {
                return ResourceManager.GetString("SheetTitle_PeriodsComparison", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Сравнение групп.
        /// </summary>
        internal static string SheetTitle_GroupsComparison {
            get {
                return ResourceManager.GetString("SheetTitle_GroupsComparison", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Сравнительный отчет по периодам.
        /// </summary>
        internal static string ReportTitle_PeriodsComparison {
            get {
                return ResourceManager.GetString("ReportTitle_PeriodsComparison", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Сравнительный отчет по группам.
        /// </summary>
        internal static string ReportTitle_GroupsComparison {
            get {
                return ResourceManager.GetString("ReportTitle_GroupsComparison", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Период.
        /// </summary>
        internal static string Label_Period {
            get {
                return ResourceManager.GetString("Label_Period", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Форма.
        /// </summary>
        internal static string Label_Form {
            get {
                return ResourceManager.GetString("Label_Form", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to №.
        /// </summary>
        internal static string Header_Number {
            get {
                return ResourceManager.GetString("Header_Number", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Вопрос.
        /// </summary>
        internal static string Header_Question {
            get {
                return ResourceManager.GetString("Header_Question", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ср зн уд j кр Упj (1), %.
        /// </summary>
        internal static string Header_SatisfactionPercent {
            get {
                return ResourceManager.GetString("Header_SatisfactionPercent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ср зн инд оц уд потр j кр (2).
        /// </summary>
        internal static string Header_AverageScore {
            get {
                return ResourceManager.GetString("Header_AverageScore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ср кв откл инд оц (3), %.
        /// </summary>
        internal static string Header_StandardDeviation {
            get {
                return ResourceManager.GetString("Header_StandardDeviation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Удовлетворенность потребителей, %.
        /// </summary>
        internal static string Header_ConsumerSatisfaction {
            get {
                return ResourceManager.GetString("Header_ConsumerSatisfaction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Оценка.
        /// </summary>
        internal static string Header_Rating {
            get {
                return ResourceManager.GetString("Header_Rating", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Кол-во ответов.
        /// </summary>
        internal static string Header_ResponseCount {
            get {
                return ResourceManager.GetString("Header_ResponseCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Кол-во.
        /// </summary>
        internal static string Header_ResponseCountShort {
            get {
                return ResourceManager.GetString("Header_ResponseCountShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Статистика.
        /// </summary>
        internal static string Header_Statistics {
            get {
                return ResourceManager.GetString("Header_Statistics", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Группа.
        /// </summary>
        internal static string Header_GroupLabel {
            get {
                return ResourceManager.GetString("Header_GroupLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Нет данных для отображения.
        /// </summary>
        internal static string NoDataMessage {
            get {
                return ResourceManager.GetString("NoDataMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to отлично.
        /// </summary>
        internal static string Rating_Excellent {
            get {
                return ResourceManager.GetString("Rating_Excellent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to хорошо.
        /// </summary>
        internal static string Rating_Good {
            get {
                return ResourceManager.GetString("Rating_Good", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to удовлетворительно.
        /// </summary>
        internal static string Rating_Satisfactory {
            get {
                return ResourceManager.GetString("Rating_Satisfactory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to неудовлетворительно.
        /// </summary>
        internal static string Rating_Unsatisfactory {
            get {
                return ResourceManager.GetString("Rating_Unsatisfactory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Итоговая удовлетворенность по анкете.
        /// </summary>
        internal static string OverallSatisfaction_Title {
            get {
                return ResourceManager.GetString("OverallSatisfaction_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Средняя удовл. потреб., %.
        /// </summary>
        internal static string OverallSatisfaction_MeanPercent {
            get {
                return ResourceManager.GetString("OverallSatisfaction_MeanPercent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Средн. ст. откл..
        /// </summary>
        internal static string OverallSatisfaction_AvgStdDev {
            get {
                return ResourceManager.GetString("OverallSatisfaction_AvgStdDev", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Итоговая оценка.
        /// </summary>
        internal static string OverallSatisfaction_Rating {
            get {
                return ResourceManager.GetString("OverallSatisfaction_Rating", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Нет данных для расчета итоговой удовлетворенности.
        /// </summary>
        internal static string OverallSatisfaction_NoData {
            get {
                return ResourceManager.GetString("OverallSatisfaction_NoData", resourceCulture);
            }
        }
    }
}
