//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Domain.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оценка должна быть в допустимом диапазоне.
        /// </summary>
        internal static string Answers_InvalidScore {
            get {
                return ResourceManager.GetString("Answers_InvalidScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вес должен быть в допустимом диапазоне.
        /// </summary>
        internal static string Answers_InvalidWeight {
            get {
                return ResourceManager.GetString("Answers.InvalidWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответ с таким id не найден.
        /// </summary>
        internal static string Answers_NotFound {
            get {
                return ResourceManager.GetString("Answers_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Должно быть указано либо текстовое значение, либо числовое.
        /// </summary>
        internal static string Answers_ValueRequired {
            get {
                return ResourceManager.GetString("Answers_ValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кафедра с таким названием уже существует.
        /// </summary>
        internal static string Departments_Duplicate {
            get {
                return ResourceManager.GetString("Departments_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К кафедре привязаны дисциплины, поэтому сначала уберите их.
        /// </summary>
        internal static string Departments_HasDisciplines {
            get {
                return ResourceManager.GetString("Departments_HasDisciplines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К кафедре привязаны преподаватели, поэтому сначала уберите их.
        /// </summary>
        internal static string Departments_HasTeachers {
            get {
                return ResourceManager.GetString("Departments_HasTeachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К кафедре привязаны пользователи, поэтому сначала уберите их.
        /// </summary>
        internal static string Departments_HasUsers {
            get {
                return ResourceManager.GetString("Departments_HasUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кафедра с таким id не найдена.
        /// </summary>
        internal static string Departments_NotFound {
            get {
                return ResourceManager.GetString("Departments_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя восстановить дисциплину, пока кафедра удалена.
        /// </summary>
        internal static string Disciplines_DepartmentDeleted {
            get {
                return ResourceManager.GetString("Disciplines_DepartmentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дисциплина с таким id не найдена.
        /// </summary>
        internal static string Disciplines_NotFound {
            get {
                return ResourceManager.GetString("Disciplines_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анкета уже активна.
        /// </summary>
        internal static string Forms_AlreadyActive {
            get {
                return ResourceManager.GetString("Forms_AlreadyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анкета уже деактивирована.
        /// </summary>
        internal static string Forms_AlreadyDeactivated {
            get {
                return ResourceManager.GetString("Forms_AlreadyDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анкета неактивна.
        /// </summary>
        internal static string Forms_Inactive {
            get {
                return ResourceManager.GetString("Forms_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анкета с данным id не существует.
        /// </summary>
        internal static string Forms_NotFound {
            get {
                return ResourceManager.GetString("Forms_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос с таким id не найден.
        /// </summary>
        internal static string Forms_QuestionNotFound {
            get {
                return ResourceManager.GetString("Forms_QuestionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос с таким порядком уже существует.
        /// </summary>
        internal static string Forms_QuestionOrderExists {
            get {
                return ResourceManager.GetString("Forms_QuestionOrderExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст не может быть пустым.
        /// </summary>
        internal static string Questions_EmptyField {
            get {
                return ResourceManager.GetString("Questions_EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Порядок должен быть неотрицательным.
        /// </summary>
        internal static string Questions_OrderInvalid {
            get {
                return ResourceManager.GetString("Questions_OrderInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К специальности привязаны специализации, поэтому сначала уберите их.
        /// </summary>
        internal static string Specialities_HasSpecializations {
            get {
                return ResourceManager.GetString("Specialities_HasSpecializations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специальность с таким id не найдена.
        /// </summary>
        internal static string Specialities_NotFound {
            get {
                return ResourceManager.GetString("Specialities_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Специализация с таким id не найдена.
        /// </summary>
        internal static string Specializations_NotFound {
            get {
                return ResourceManager.GetString("Specializations_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя восстановить специализацию, пока специальность удалена.
        /// </summary>
        internal static string Specializations_SpecialityDeleted {
            get {
                return ResourceManager.GetString("Specializations_SpecialityDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уже отправляли ответ на эту анкету с выбранными параметрами.
        /// </summary>
        internal static string Submissions_AlreadySubmitted {
            get {
                return ResourceManager.GetString("Submissions_AlreadySubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уже есть ответ на вопрос.
        /// </summary>
        internal static string Submissions_AnswerExists {
            get {
                return ResourceManager.GetString("Submissions_AnswerExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ответ с таким id не найден.
        /// </summary>
        internal static string Submissions_AnswerNotFound {
            get {
                return ResourceManager.GetString("Submissions_AnswerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение не может быть больше веса для вопроса.
        /// </summary>
        internal static string Submissions_InvalidWeight {
            get {
                return ResourceManager.GetString("Submissions_InvalidWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправка с таким id не найдена.
        /// </summary>
        internal static string Submissions_NotFound {
            get {
                return ResourceManager.GetString("Submissions_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К преподавателю привязаны пользователи, поэтому сначала уберите их.
        /// </summary>
        internal static string Teachers_HasUsers {
            get {
                return ResourceManager.GetString("Teachers_HasUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Преподаватель с таким id не найден.
        /// </summary>
        internal static string Teachers_NotFound {
            get {
                return ResourceManager.GetString("Teachers_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время жини reset tokenа прошло .
        /// </summary>
        internal static string Users_ExpiredResetToken {
            get {
                return ResourceManager.GetString("Users_ExpiredResetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа с таким логином уже существует.
        /// </summary>
        internal static string Users_GroupExists {
            get {
                return ResourceManager.GetString("Users_GroupExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название группы не валидно (должно быть меньше 5 символов).
        /// </summary>
        internal static string Users_GroupNameInvalid {
            get {
                return ResourceManager.GetString("Users_GroupNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невалидный либо прошедшний Reset Token.
        /// </summary>
        internal static string Users_InvalidResetToken {
            get {
                return ResourceManager.GetString("Users_InvalidResetToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким id не найден.
        /// </summary>
        internal static string Users_NotFound {
            get {
                return ResourceManager.GetString("Users_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с таким логином не найден.
        /// </summary>
        internal static string Users_NotFoundByLogin {
            get {
                return ResourceManager.GetString("Users_NotFoundByLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не авторизованы для выполняния этого действия.
        /// </summary>
        internal static string Users_Unauthorized {
            get {
                return ResourceManager.GetString("Users_Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь уже существует.
        /// </summary>
        internal static string Users_UserExist {
            get {
                return ResourceManager.GetString("Users_UserExist", resourceCulture);
            }
        }
    }
}
