<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SharedKernel\SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Throw" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\DomainErrors.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>DomainErrors.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\DomainErrors.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DomainErrors.resx</DependentUpon>
    </Compile>
  </ItemGroup>


</Project>
