//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AnalyticsFilterResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnalyticsFilterResources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Resources.AnalyticsFilterResources", typeof(AnalyticsFilterResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Преподаватель.
        /// </summary>
        internal static string Filter_Teacher {
            get {
                return ResourceManager.GetString("Filter_Teacher", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Дисциплина.
        /// </summary>
        internal static string Filter_Discipline {
            get {
                return ResourceManager.GetString("Filter_Discipline", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Кафедра.
        /// </summary>
        internal static string Filter_Department {
            get {
                return ResourceManager.GetString("Filter_Department", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Специальность.
        /// </summary>
        internal static string Filter_Speciality {
            get {
                return ResourceManager.GetString("Filter_Speciality", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Специализация.
        /// </summary>
        internal static string Filter_Specialization {
            get {
                return ResourceManager.GetString("Filter_Specialization", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Организация.
        /// </summary>
        internal static string Filter_Organization {
            get {
                return ResourceManager.GetString("Filter_Organization", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Форма обучения.
        /// </summary>
        internal static string Filter_EducationForm {
            get {
                return ResourceManager.GetString("Filter_EducationForm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Категория сотрудника.
        /// </summary>
        internal static string Filter_EmployeeCategory {
            get {
                return ResourceManager.GetString("Filter_EmployeeCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Должность.
        /// </summary>
        internal static string Filter_Position {
            get {
                return ResourceManager.GetString("Filter_Position", resourceCulture);
            }
        }
    }
}
