@host = http://localhost:5000
@contentType = application/json

# ==========================================
# 1. Логин АДМИНИСТРАТОРА
# ==========================================
# @name loginAdmin
POST {{host}}/users/login
Content-Type: {{contentType}}

{
    "login": "ADMIN",
    "password": "12345678"
}

###
# @adminToken = {{loginAdmin.response.body}}
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJkZXZlbG9wZXJzIiwiaXNzIjoicXVlc3Rpb25uYWlyZS12ZmJzYWMiLCJleHAiOjE3NjY1OTI4NDYsInN1YiI6ImEwYWRmYmEyLWQ3OWItNGU4Ny05MWEwLTdhMTI4ZmFkYWZlMCIsImlhdCI6MTc2NjU4OTI0NiwibmJmIjoxNzY2NTg5MjQ2fQ.eb-WQ5-XeR8KmC-1DGi_zXTwYw-WXoJ6PBtNutZMfhI

# ==========================================
# 2. Логин СТУДЕНЧЕСКОЙ ГРУППЫ (ПО111)
# ==========================================
# @name loginStudent
POST {{host}}/users/login
Content-Type: {{contentType}}

{
    "login": "ПО111",
    "password": "12345678"
}

###
@studentToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJkZXZlbG9wZXJzIiwiaXNzIjoicXVlc3Rpb25uYWlyZS12ZmJzYWMiLCJleHAiOjE3NjY1OTI4NDYsInN1YiI6ImEwYWRmYmEyLWQ3OWItNGU4Ny05MWEwLTdhMTI4ZmFkYWZlMCIsImlhdCI6MTc2NjU4OTI0NiwibmJmIjoxNzY2NTg5MjQ2fQ.eb-WQ5-XeR8KmC-1DGi_zXTwYw-WXoJ6PBtNutZMfhI


# ==========================================
# 3. Получение информации о текущем пользователе
# ==========================================
GET {{host}}/users/me
Authorization: Bearer {{studentToken}}