@host = http://localhost:5000
@token = {{loginStudent.response.body}}

# ==========================================
# 1. Список кафедр
# ==========================================
GET {{host}}/departments
Authorization: Bearer {{token}}

###

# ==========================================
# 2. Список дисциплин
# ==========================================
GET {{host}}/disciplines
Authorization: Bearer {{token}}