name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "10.x"
  SOLUTION: "src/Questionnaire.slnx"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION }} --configuration Release --no-restore

      - name: Test
        run: dotnet test ${{ env.SOLUTION }} --configuration Release --no-restore --no-build

      - name: Publish
        run: dotnet publish ${{ env.SOLUTION }} --configuration Release --no-restore --no-build
